Reverts [8a6041f](https://github.com/google-pytorch/torch_tpu/commit/8a6041f6a187dd71adf074107cb11e3920c893dc) because it broke OSS nightly due to incomplete GCS setup:
```
FileNotFoundError: GCS bucket data directory '/tmp/gcsfuse/data' does not exist. Ensure GCS bucket 'torchtpu-shared' is mounted at '/tmp/gcsfuse/data'.
```

https://btx.cloud.google.com/invocations/8abafefb-e096-449b-8ba4-cedd421755c9/targets

Generated from cl/970107596

PiperOrigin-RevId: 970107596