Avoid in-place update for RNG state tensor
With this change, when we need to modify the RNG state we always replace the state at::Tensor with a new at::Tensor.
On the contrary, the original code would update the RNG state tensor in-place, by replacing its associated TPU buffer by calling AssignBufferToAtTensor. That caused test case examples/benchmarks:ml_layers_test_tpu to be flaky and fail with this error:

File "torch_tpu/api/_device_module.py", line 116, in manual_seed_all
    _device_ops_backend.manual_seed_all(seed)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
PiperOrigin-RevId: 872752925